services:
  broker:
    image: apache/kafka:latest
    container_name: broker
    ports:
      - "9092:9092"
      - "19092:19092"
      - "29092:29092"
      - "9093:9093"
      - "19093:19093"
      - "29093:29093"
    networks:
      - airflow-kafka-network
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://broker:9092,CONTROLLER://broker:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@broker:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3


# KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
# KAFKA_ADVERTISED_LISTENERS: INSIDE://broker:9092,OUTSIDE://localhost:9092
# KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9092
# KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE

# services:
#   broker:
#     image: apache/kafka:latest
#     container_name: broker
#     environment:
#       KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
#       KAFKA_ADVERTISED_LISTENERS: INSIDE://broker:9092,OUTSIDE://localhost:29092
#       KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:29092





# services:
#   broker:
#     image: apache/kafka:latest
#     container_name: broker
#     networks:
#       - airflow-kafka-network
#     # environment:
#     #   KAFKA_NODE_ID: 1
#     #   KAFKA_PROCESS_ROLES: broker,controller
#     #   KAFKA_LISTENERS: PLAINTEXT://localhost:9092,CONTROLLER://localhost:9093
#     #   KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
#     #   KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
#     #   KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
#     #   KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
#     #   KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
#     #   KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
#     #   KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
#     #   KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
#     #   KAFKA_NUM_PARTITIONS: 3




# services:
#   controller-1:
#     image: apache/kafka:latest
#     container_name: controller-1
#     environment:
#       KAFKA_NODE_ID: 1
#       KAFKA_PROCESS_ROLES: controller
#       KAFKA_LISTENERS: CONTROLLER://:9093
#       KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
#       KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
#       KAFKA_CONTROLLER_QUORUM_VOTERS: 1@controller-1:9093,2@controller-2:9093,3@controller-3:9093
#       KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

#   controller-2:
#     image: apache/kafka:latest
#     container_name: controller-2
#     environment:
#       KAFKA_NODE_ID: 2
#       KAFKA_PROCESS_ROLES: controller
#       KAFKA_LISTENERS: CONTROLLER://:9093
#       KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
#       KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
#       KAFKA_CONTROLLER_QUORUM_VOTERS: 1@controller-1:9093,2@controller-2:9093,3@controller-3:9093
#       KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

#   controller-3:
#     image: apache/kafka:latest
#     container_name: controller-3
#     environment:
#       KAFKA_NODE_ID: 3
#       KAFKA_PROCESS_ROLES: controller
#       KAFKA_LISTENERS: CONTROLLER://:9093
#       KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
#       KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
#       KAFKA_CONTROLLER_QUORUM_VOTERS: 1@controller-1:9093,2@controller-2:9093,3@controller-3:9093
#       KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

#   broker-1:
#     image: apache/kafka:latest
#     container_name: broker-1
#     ports:
#       - 29092:9092
#     environment:
#       KAFKA_NODE_ID: 4
#       KAFKA_PROCESS_ROLES: broker
#       KAFKA_LISTENERS: 'PLAINTEXT://:19092,PLAINTEXT_HOST://:9092'
#       KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://broker-1:19092,PLAINTEXT_HOST://localhost:29092'
#       KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
#       KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
#       KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
#       KAFKA_CONTROLLER_QUORUM_VOTERS: 1@controller-1:9093,2@controller-2:9093,3@controller-3:9093
#       KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
# # listeners=PLAINTEXT://:9092,DOCKER_HACK://:19092
# # advertised.listeners=PLAINTEXT://localhost:9092,DOCKER_HACK://host.docker.internal:19092
# # listener.security.protocol.map=PLAINTEXT:PLAINTEXT,DOCKER_HACK:PLAINTEXT
#       # KAFKA_LISTENERS: 'PLAINTEXT://:9092,DOCKER_HACK://:19092'
#       # KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://localhost:9092,DOCKER_HACK://host.docker.internal:19092'
#       # KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,DOCKER_HACK:PLAINTEXT

#     depends_on:
#       - controller-1
#       - controller-2
#       - controller-3

#   broker-2:
#     image: apache/kafka:latest
#     container_name: broker-2
#     ports:
#       - 39092:9092
#     environment:
#       KAFKA_NODE_ID: 5
#       KAFKA_PROCESS_ROLES: broker
#       KAFKA_LISTENERS: 'PLAINTEXT://:19092,PLAINTEXT_HOST://:9092'
#       KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://broker-2:19092,PLAINTEXT_HOST://localhost:39092'
#       KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
#       KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
#       KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
#       KAFKA_CONTROLLER_QUORUM_VOTERS: 1@controller-1:9093,2@controller-2:9093,3@controller-3:9093
#       KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
#     depends_on:
#       - controller-1
#       - controller-2
#       - controller-3

#   broker-3:
#     image: apache/kafka:latest
#     container_name: broker-3
#     ports:
#       - 49092:9092
#     environment:
#       KAFKA_NODE_ID: 6
#       KAFKA_PROCESS_ROLES: broker
#       KAFKA_LISTENERS: 'PLAINTEXT://:19092,PLAINTEXT_HOST://:9092'
#       KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://broker-3:19092,PLAINTEXT_HOST://localhost:49092'
#       KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
#       KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
#       KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
#       KAFKA_CONTROLLER_QUORUM_VOTERS: 1@controller-1:9093,2@controller-2:9093,3@controller-3:9093
#       KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
#     depends_on:
#       - controller-1
#       - controller-2
#       - controller-3
